--Basic data insights 
use DataWarehouse
go 
select * from gold.dim_products;
--select * from gold.dim_customer;
select * from gold.fact_sales;

-- Explore all objects in the database
select * from INFORMATION_SCHEMA.TABLES

--Explore all the columns  in the database
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='dim_customer'

--==========Customer table==============----
--1: Explore all countries our customers come from..
select distinct  
country 
from gold.dim_customer;

--2: Explore all categories and sub category and product "all major division"
select DISTINCT
    category,
    subcategory,
    product_name
from gold.dim_products
order by 1,2,3;

--3:Find the date of first and last order
--4: how many years or month of sales are avaliable
SELECT 
    min(order_date) as first_order_date,
    max(order_date) as last_order_date,
    DATEDIFF(year,MIN(order_date),max(order_date))as order_range_years
from gold.fact_sales;

--5: select the youngest and the oldest customer 
select 
min(birthdate) as oldest_client,
DATEDIFF(year,min(birthdate),GETDATE()) as oldest_age,
max(birthdate) as youngest_client,
DATEDIFF(year,max(birthdate),GETDATE()) as youngest_age
from gold.dim_customer

--6:find total number of products
select count(product_id) as total_products from gold.dim_products;
select count(distinct product_id) as total_products from gold.dim_products;
--7:Find total number of customers
select count(customer_id) as total_customers from gold.dim_customer;
--8: Find the avg selling price 
select avg(price) as avg_price from gold.fact_sales;
--9: Findthe total sales
select sum(sales_amount) as total_sales from gold.fact_sales;
--10: find how many items are sold 
select sum(quantity) as total_quantity from gold.fact_sales;
--11: find total number of orders
select count(order_number) as total_orders from gold.fact_sales
select count(distinct order_number) as total_orders from gold.fact_sales
--12: find total number of customers that has placed an order
select count(distinct customer_key) as total_customers from gold.fact_sales;

--generate a report  that shows all key matrics of the business
select 'Total Sales' as measure_name,sum(sales_amount) as measure_value from gold.fact_sales
union all 
select 'Total Quantity' as measure_name,sum(quantity) as measure_value from gold.fact_sales
union all
select 'Average Price' as measure_name,avg(price) as measure_value from gold.fact_sales
UNION ALL
select 'No of products' as measure_name, count(product_id) as measure_value from gold.dim_products
UNION ALL
select 'No of customers' as measure_name, count(customer_id) as measure_value from gold.dim_customer
UNION ALL
select 'No of orders' as measure_name, count(distinct order_number) as measure_value from gold.fact_sales


--==============Magnitude Analysis===============--
--comparing a measure value by categeries
--1: find total customers by countries
    select country,count(customer_key) as total_customers
    from gold.dim_customer
    group by country
    order by total_customers DESC
--2: find total customers by gender 
    select gender,count(customer_key) as total_customers
    from gold.dim_customer
    group by gender;
--3: find total products by categories
    select category,count(product_id) as total_products
    from gold.dim_products
    group by category
    order by total_products desc
--4: what is the avg costs in each category?
    select category,avg(cost) as avg_cost
    from gold.dim_products
    group by category
    order by avg_cost desc
--5: what is the total revenue generated for each category?
    select
        p.category,
        sum(f.sales_amount) as total_revenue
    from gold.fact_sales f    
    left join gold.dim_products p   
    on f.product_key=p.product_key
    GROUP BY p.category
    order by total_revenue DESC
--6:find total revenue is generated by each customer
select
        c.customer_id,
        c.first_name,
        c.last_name,
        sum(f.sales_amount) as total_revenue
    from gold.fact_sales f    
    left join gold.dim_customer c  
    on f.customer_key=c.customer_key
    GROUP BY c.customer_id,c.first_name, c.last_name
    order by total_revenue DESC

--7: what is the distribution of sold items across countries?

select
        c.country,
        sum(f.quantity) as total_sold_items
    from gold.fact_sales f    
    left join gold.dim_customer c  
    on f.customer_key=c.customer_key
    GROUP BY c.country
    order by total_sold_items DESC

---------========Ranking==================================
--1: which 5 products generate the highest revenue?
select top 5
        p.product_name,
        sum(f.sales_amount) as total_revenue
    from gold.fact_sales f    
    left join gold.dim_products p   
    on f.product_key=p.product_key
    GROUP BY p.product_name 
    ORDER BY total_revenue DESC

--or

select top 5
        p.product_name,
        sum(f.sales_amount) as total_revenue,
        ROW_NUMBER()over(ORDER by sum(f.sales_amount)DESC) as rank_product
    from gold.fact_sales f    
    left join gold.dim_products p   
    on f.product_key=p.product_key
    GROUP BY p.product_name 



--2: what are the 5 worst performing products in terms of sales?
select top 5
        p.product_name,
        sum(f.sales_amount) as total_revenue
    from gold.fact_sales f    
    left join gold.dim_products p   
    on f.product_key=p.product_key
    GROUP BY p.product_name 
    ORDER BY total_revenue ASC

--3 find the top 10 customers with highest revenue
select top 10
        c.first_name,
        c.last_name,
        sum(f.sales_amount) as total_revenue
    from gold.fact_sales f    
    left join gold.dim_customer c  
    on f.customer_key=c.customer_key
    GROUP BY c.first_name,c.last_name
    ORDER BY total_revenue DESC

--4: the 3 customers with fewest order
select top 3
        c.first_name,
        c.last_name,
        count(distinct order_number) as total_orders
    from gold.fact_sales f    
    left join gold.dim_customer c  
    on f.customer_key=c.customer_key
    GROUP BY c.first_name,c.last_name
    ORDER BY total_orders ASC
